name: Build Dumper-7

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install xmake
        uses: xmake-io/github-action-setup-xmake@v1

      - name: Build
        shell: pwsh
        run: |
          xmake f -p windows -a x64 -m release
          xmake build

      - name: Upload DLL
        uses: actions/upload-artifact@v4
        with:
          name: Dumper-7
          path: Bin/Release/*
